### ISSUE TITLE
Cypher query

### ISSUE THREAD

**Issue by ksecurity45** [wh1t3p1g/tabby-vul-finder#4]
I am looking for a working Cypher query that calls the procedure tabby.algo.findPath. Can you help me with that?

When defining the source, I want to include all methods that take a String as a parameter and extend java.rmi.Remote. So all methods which can be called in RMI and take atlest one string parameter are my source The sink method should be executeQuery.

Please fill in the following template:

name: "web_to_code"
type: "web"
source:
  type: "source"
  endpoint: true
sink:
  type: "sink"
  sink: true
  vul: "CODE"
depth: 8
limit: 10
procedure: "tabby.algo.findPath"
sourceBlacklists: []
pathBlacklists:
  - "java.lang.Iterable#forEach"

**Comment by ksecurity45** [comment]
For example i know 

getFunctionByCode is a method which is in class which extends remote and sink is called but this does not return any data.


match (source:Method {NAME:"getFunctionByCode"}) 
match (sink:Method {NAME:"executeQuery"}) 
call tabby.algo.findPath(source, "-", sink, 8, false) YIELD path
return path

**Comment by wh1t3p1g** [comment]
First, try to comfirm the cypher you provided will return correct data. Then, try to use `cypher` configuration to set a more custom usage. The case like https://github.com/wh1t3p1g/tabby-vul-finder/blob/main/rules/benchmark/cc4-aj.yml#L6
According you provided, use yaml like
```
name: "web_to_sql"
enable: true
type: "web"
source:
  type: "source"
  cypher: "match (source:Method {NAME:\"getFunctionByCode\"})"
sink:
  type: "sink"
  sink: true
  name: "executeQuery"
depth: 10
limit: 1
direct: "-"
procedure: "tabby.algo.findPath"
sourceBlacklists: []
pathBlacklists: []
```
Also, use a more simple usage, like
```
name: "web_to_sql"
enable: true
type: "web"
source:
  type: "source"
  name: "getFunctionByCode"
sink:
  type: "sink"
  sink: true
  name: "executeQuery"
depth: 10
limit: 1
direct: "-"
procedure: "tabby.algo.findPath"
sourceBlacklists: []
pathBlacklists: []
```

**Comment by ksecurity45** [comment]
I have tested this one. 

The file : cyphers.yml
```
name: "web_to_sql"
enable: true
type: "web"
source:
  type: "source"
  name: "getFunctionByCode"
sink:
  type: "sink"
  sink: true
  name: "executeQuery"
depth: 10
limit: 1
direct: "-"
procedure: "tabby.algo.findPath"
sourceBlacklists: []
pathBlacklists: []
```

Using command : java -jar tabby-vul-finder.jar query khan rules/cyphers.yml


<img width="1149" alt="image" src="https://github.com/user-attachments/assets/8935dad5-a962-4b64-8c56-32dc5bf107e8">


<img width="956" alt="image" src="https://github.com/user-attachments/assets/5e44eaf6-88be-4ecb-b966-f096a29d0722">

Any idea why this procedure tabby.algo.findPath is not working ? 

```
match (source:Method {HAS_PARAMETERS:true}) where source.NAME = "getFunctionByCode" 
match (sink:Method {HAS_PARAMETERS:true}) where sink.NAME = "executeQuery" 
CALL tabby.algo.findPath(source, "-", sink, 10, false) YIELD path
return path 
```
